from tkinter import *
from PIL import ImageTk, Image
root  = Tk()
root.config(bg="white")
root.minsize(width=1000,height=1000)
img = ImageTk.PhotoImage(Image.open("logo.png"))
canvas = Canvas(height=200,width=190)
canvas.config(bg="white",highlightthickness=0)
canvas.create_image(100, 95, image=img)
canvas.place(x =350,y =200)
website = Label(text="WEBSITE Name:")
website.config(bg="white",font=("arial",20,"normal"))
website.place(x=200,y=500)
Website = Entry()
Website.place(x =400,y =500)
Email = Label(text="Email address:")
Email.config(bg="white",font=("arial",20,"normal"))
Email.place(x=200,y=500)
Email = Entry()
Email.place(x =400,y =500)
mainloop()